Repository DibiDibiDeep/Final-ml, pull requests merged in 2024-09, with the labels that each got.

#10 Feature/babydiary
  router/babydiary/README.md
  router/babydiary/babydiary.py
  router/babydiary/prompts/prompts.py
  router/babydiary/requirements.txt
Labels: enhancement

#24 [기능개선] 캘린더 api 형식 변경(input: user_id, baby_id 추가, output: year, month ,time, information 추가) & s3 이미지 다운로드 로직
  README.md
  app/api/calendar/calendar.py
  app/api/calendar/models.py
  app/api/calendar/prompts/calendar_betterocr_ver2.txt
  app/api/calendar/utils/s3_util.py
  requirements.txt
Labels: 기능개선

#26 [기능개선]알림장 요약 api 형식변경(Request: user_id, baby_id 추가, Response: user_id, baby_id, role(부모,자식) 추가)
  README.md
  app/api/babydiary/babydiary.py
Labels: 기능개선

#28 [기능개선] 캘린더 api 올바른 유형 이미지 판단 & OCR 과정 중 에러 발생 시 Error raise
  app/api/calendar/BetterOCR/betterocr/detect.py
  app/api/calendar/calendar.py
Labels: 기능개선

#30 [기능추가]동화생성 기능 구현
  app/api/fairytale/fairytale.py
  app/api/fairytale/models.py
  app/api/fairytale/prompts/fairytale_prompt_ver1.txt
  app/api/fairytale/utils/fairytale_image_utils.py
  app/api/fairytale/utils/fairytale_utils.py
  app/main.py
Labels: 기능추가

#32 [리팩토링]동화생성 생성 삽화 url 짧게 만들기
  app/api/fairytale/fairytale.py
  app/api/fairytale/utils/fairytale_image_utils.py
  requirements.txt
Labels: 리팩토링

#34 [리팩토링]알림장 api Request user_id, baby_id 데이터 유형 변경
  app/api/babydiary/babydiary.py
Labels: 리팩토링

#35 [기능개선]하루요약 챗봇 Prompt Injection 공격 방어 프롬프트 추가
  app/api/daysummary/daysumm.py
Labels: 기능개선, 리팩토링

#38 [기능수정]하루요약 챗봇 Request, Response valuee user_id,baby_id 추가
  app/api/daysummary/daysumm.py
Labels: 기능수정

#42 [기능개선]캘린더 Response key 추가 및 프롬프트 개선 & Warning 이슈 해결
  app/api/calendar/calendar.py
  app/api/calendar/models.py
  app/api/calendar/prompts/calendar_betterocr_ver3.txt
  app/api/daysummary/config.py
  app/api/daysummary/daysumm.py
Labels: 기능개선

#46 [리팩토링]인자값 환경변수로 통제, Agent 고도화, retreiver_about_qeustion user_id, baby_id 필터값 추가
  Dockerfile
  app/api/daysummary/config.py
  app/api/daysummary/daysumm.py
  app/api/daysummary/tools.py
  app/api/daysummary/utils/get_data.py
  app/api/daysummary/utils/insert_db.py
Labels: 리팩토링

#44 [기능개선] 동화생성 API 1차 프롬프트 엔지니어링 고도화
  app/api/fairytale/fairytale.py
  app/api/fairytale/models.py
  app/api/fairytale/prompts/fairytale_prompt_ver2.txt
  app/api/fairytale/utils/fairytale_image_utils.py
  app/api/fairytale/utils/fairytale_utils.py
Labels: 기능개선

#47 [기능개선]하루요약 챗봇 벡터디비 분리에 따른 변경 & Retrieval Tool 구동방식 변경 & Agent Prompt 고도화
  Dockerfile
  app/api/daysummary/config.py
  app/api/daysummary/daysumm.py
  app/api/daysummary/tools.py
  app/api/daysummary/utils/get_data.py
  app/api/daysummary/utils/insert_db.py
Labels: 기능추가, 기능개선, 기능수정

#49 [기능개선]동화생성 api 이미지생성 비동기 처리
  app/api/fairytale/fairytale.py
  app/api/fairytale/prompts/fairytale_prompt_ver2.txt
  app/api/fairytale/utils/fairytale_image_utils.py
Labels: 기능개선

#51 [기능추가]Milvus 벡터디비 Embedding&Insert API
  app/api/daysummary/config.py
  app/api/daysummary/utils/init_db.py
  app/api/embedding/embedd.py
  app/api/embedding/models.py
  app/api/embedding/utils/vecdb_util.py
  app/main.py
Labels: 기능추가, 기능개선

#56 [기능개선]알림장 요약 API 유효하지 않은 입력 알림장 예외처리 & Response 값 키워드 내용 Optional None
  app/api/babydiary/babydiary.py
  app/api/babydiary/models.py
  app/api/babydiary/prompts.py
Labels: 기능개선

#54 [기능개선]하루 요약 챗봇: 사용자 하루 정보 get 로직 변경
  app/api/daysummary/daysumm.py
  app/api/daysummary/utils/get_data.py
Labels: 기능개선

#53 [기능추가] 음성메모: Whisper 초기 api 작성
  .gitignore
  app/api/audiomemo/audiomemo.py
  app/api/babydiary/babydiary.py
  app/main.py
Labels: 기능추가

#57 [기능개선]하루요약 챗봇 프롬프트엔지니어링(자연스러운 대화흐름, Prompt Injection)
  app/api/daysummary/daysumm.py
  app/api/daysummary/prompts/daysummary_prompt_ver1.txt
  app/api/daysummary/prompts/daysummary_prompt_ver2.txt
  app/api/daysummary/prompts/daysummary_prompt_ver3.txt
  app/api/daysummary/tools.py
Labels: 기능개선
